name: stash_hive
version: 1.0.1
description: >-
  Hive storage extension for the stash caching API. Provides support to store caches
  in the Hive database
homepage: https://github.com/ivoleitao/stash_hive

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  hive: ^1.4.4
  stash: ^1.0.0
  #stash:
  #  path: ../stash

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
  test_coverage: ^0.4.3
