name: stash_hive
version: 1.0.2
description: >-
  Hive storage extension for the stash caching API. Provides support to store caches
  in the Hive database
homepage: https://github.com/ivoleitao/stash_hive

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  hive: ^1.6.0-nullsafety.2
    #  stash: ^1.0.2
  stash:
    path: ../stash

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.4
  # test_coverage: ^0.4.3
