name: stash_hive
version: 1.0.0-dev.3
description: >-
  Hive storage extension for the stash caching API. Provides support to store caches
  in the Hive database
homepage: https://github.com/ivoleitao/stash_hive

environment:
  sdk: ">=2.8.4 <3.0.0"

dependencies:
  hive: 1.4.1+1
  stash: ^1.0.0-dev.2
  #stash:
  #  path: ../stash

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
  test_coverage: ^0.4.3
